// <auto-generated />
namespace ITPROEKT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m_33257 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m_33257));
        
        string IMigrationMetadata.Id
        {
            get { return "202009112003293_m_33257"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
