// <auto-generated />
namespace ITPROEKT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class order_mg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order_mg));
        
        string IMigrationMetadata.Id
        {
            get { return "202009091248188_order_mg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
